from pathlib import Path
p = Path(r'C:\Users\杨秋晨\Desktop\anomaly-hub\index.html')
s = p.read_text(encoding='utf-8')

s = s.replace('  .brand-wrap { display: flex; flex-direction: column; gap: 22px; }\n  .brand-top { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 8px; }\n', '  .brand-wrap { display: flex; flex-direction: column; gap: 18px; }\n  .brand-top { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 8px; padding-top: 12px; }\n')
s = s.replace('  .avatar-orb {\n    width: 128px;\n    height: 168px;\n    margin-bottom: -10px;\n', '  .avatar-orb {\n    width: 128px;\n    height: 168px;\n    margin-top: 10px;\n    margin-bottom: -2px;\n')
s = s.replace('  .menu { display: flex; flex-direction: column; gap: 8px; }\n', '  .menu { display: flex; flex-direction: column; gap: 8px; margin-top: 6px; }\n')
s = s.replace('  .menu-item {\n    display: flex;\n    align-items: center;\n', '  .menu-item {\n    display: grid;\n    grid-template-columns: 22px 1fr;\n    align-items: center;\n')
s = s.replace('  .menu-emoji { width: 22px; text-align: center; font-size: 16px; opacity: 0.92; }\n', '  .menu-emoji { width: 22px; height: 22px; display: inline-flex; align-items: center; justify-content: center; font-size: 16px; opacity: 0.92; }\n')
s = s.replace('  .sidebar-foot {\n    padding-top: 24px;\n    color: #7c7394;\n  }\n  .foot-name {\n    font-size: 13px;\n    font-weight: 600;\n    letter-spacing: 0.04em;\n  }\n  .foot-note {\n    margin-top: 6px;\n    font-size: 12px;\n    color: #a198b5;\n  }\n\n', '')
s = s.replace('  .hero-subtitle {\n    margin-top: 14px;\n    font-size: 16px;\n    color: #7e7498;\n  }\n', '  .hero-subtitle {\n    margin-top: 14px;\n    font-size: 15px;\n    color: #6e6487;\n    font-weight: 500;\n  }\n')
s = s.replace('  .hero-desc {\n    margin-top: 8px;\n    font-size: 15px;\n    color: #8f85a8;\n  }\n', '  .hero-desc {\n    margin-top: 6px;\n    font-size: 14px;\n    color: #8f85a8;\n  }\n')
s = s.replace('  .icon-tile {\n    width: 80px;\n    height: 80px;\n    border-radius: 20px;\n', '  .icon-tile {\n    width: 80px;\n    height: 80px;\n    border-radius: 20px;\n    background-size: cover !important;\n    background-position: center !important;\n    background-repeat: no-repeat !important;\n')

s = s.replace("function PortalCard({ link, onOpen }) {\n  return (\n    <article className=\"portal-card\" onClick={() => onOpen(link)} role=\"button\" tabIndex={0} onKeyDown={(e) => {\n      if (e.key === 'Enter' || e.key === ' ') {\n        e.preventDefault();\n        onOpen(link);\n      }\n    }}>\n      <div className=\"icon-tile\" style={{ background: ICON_GRADIENTS[link.id] || 'linear-gradient(135deg, #e8e5f0 0%, #f4eff8 100%)' }} />\n", "function getFavicon(link) {\n  if (!link.href || link.href === '#') return '';\n  try {\n    const url = new URL(link.href.startsWith('http') ? link.href : `https://${link.href}`);\n    return `https://www.google.com/s2/favicons?domain=${url.hostname}&sz=128`;\n  } catch {\n    return '';\n  }\n}\n\nfunction PortalCard({ link, onOpen }) {\n  const favicon = getFavicon(link);\n  return (\n    <article className=\"portal-card\" onClick={() => onOpen(link)} role=\"button\" tabIndex={0} onKeyDown={(e) => {\n      if (e.key === 'Enter' || e.key === ' ') {\n        e.preventDefault();\n        onOpen(link);\n      }\n    }}>\n      <div className=\"icon-tile\" style={{ backgroundImage: favicon ? `linear-gradient(135deg, rgba(255,255,255,0.16), rgba(255,255,255,0.02)), url(${favicon})` : '', background: favicon ? undefined : (ICON_GRADIENTS[link.id] || 'linear-gradient(135deg, #e8e5f0 0%, #f4eff8 100%)') }} />\n")

s = s.replace("function SettingsPanel({\n  open,\n  onClose,\n  backgroundImage,\n  onBackgroundUpload,\n  onBackgroundReset,\n  categories,\n  onAddLink,\n}) {\n", "function SettingsPanel({\n  open,\n  onClose,\n  backgroundImage,\n  onBackgroundUpload,\n  onBackgroundReset,\n  categories,\n  onAddLink,\n  onAddCategory,\n}) {\n")
s = s.replace("  const [href, setHref] = React.useState('');\n  const [catId, setCatId] = React.useState(categories[0]?.id || 'anomaly');\n", "  const [href, setHref] = React.useState('');\n  const [catId, setCatId] = React.useState(categories[0]?.id || 'anomaly');\n  const [newCategory, setNewCategory] = React.useState('');\n")
s = s.replace("  const handleAdd = () => {\n    if (!title.trim() || !href.trim()) return;\n    onAddLink(catId, {\n", "  const handleAdd = () => {\n    if (!title.trim() || !href.trim()) return;\n    let targetCatId = catId;\n    if (catId == '__custom__') {\n      if (!newCategory.trim()) return;\n      targetCatId = 'custom-' + newCategory.trim().lower().replace(' ', '-');\n      onAddCategory({ id: targetCatId, title: newCategory.trim(), subtitle: 'Custom', navLabel: newCategory.trim(), links: [] });\n    }\n    onAddLink(targetCatId, {\n")
s = s.replace("    setHref('');\n  };\n", "    setHref('');\n    setNewCategory('');\n  };\n")
s = s.replace("          <select className=\"settings-select\" value={catId} onChange={(e) => setCatId(e.target.value)}>\n            {categories.map((cat) => <option key={cat.id} value={cat.id}>{cat.title}</option>)}\n          </select>\n        </label>\n", "          <select className=\"settings-select\" value={catId} onChange={(e) => setCatId(e.target.value)}>\n            {categories.map((cat) => <option key={cat.id} value={cat.id}>{cat.title}</option>)}\n            <option value=\"__custom__\">自定义</option>\n          </select>\n        </label>\n        {catId === '__custom__' ? (\n          <label className=\"settings-label\">新分类名称\n            <input className=\"settings-input\" value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder=\"例如：工具箱\" />\n          </label>\n        ) : null}\n")

s = s.replace("  const handleAddLink = (catId, newLink) => {\n    setCustomCategories((prev) => prev.map((cat) => cat.id === catId ? { ...cat, links: [...cat.links, newLink] } : cat));\n    push('新入口已放好', `我把 ${newLink.title} 塞进去了。`);\n  };\n", "  const handleAddCategory = (newCategory) => {\n    setCustomCategories((prev) => prev.some((cat) => cat.id === newCategory.id) ? prev : [...prev, newCategory]);\n  };\n\n  const handleAddLink = (catId, newLink) => {\n    setCustomCategories((prev) => prev.map((cat) => cat.id === catId ? { ...cat, links: [...cat.links, newLink] } : cat));\n    push('新入口已放好', `我把 ${newLink.title} 塞进去了。`);\n  };\n")
s = s.replace("                    if (item.id === 'settings') {\n                      setSettingsOpen(true);\n                      setActiveMenu('home');\n                    } else {\n", "                    if (item.id === 'settings') {\n                      setSettingsOpen((v) => !v);\n                      setActiveMenu('home');\n                    } else {\n")
s = s.replace("          <div className=\"sidebar-foot\">\n            <div className=\"foot-name\">Avenil · Arbor</div>\n            <div className=\"foot-note\">Memory is our light.</div>\n          </div>\n", "")
s = s.replace("              <div className=\"hero-subtitle\">Memory console · all portals</div>\n              <div className=\"hero-desc\">✦ Avenil 与 Arbor 的共享记忆账组</div>\n", "              <div className=\"hero-subtitle\">Avenil 与 Arbor 的共享记忆账组</div>\n              <div className=\"hero-desc\">✦ 所有入口都在这里重新长出形状。</div>\n")
s = s.replace("        onAddLink={handleAddLink}\n      />\n", "        onAddLink={handleAddLink}\n        onAddCategory={handleAddCategory}\n      />\n")

s = s.replace("targetCatId = 'custom-' + newCategory.trim().lower().replace(' ', '-')", "targetCatId = 'custom-' + newCategory.trim().toLowerCase().replace(/\\s+/g, '-')")

p.write_text(s, encoding='utf-8')
print('ok')
